name: Metrics
on:
  # schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Contributors and sponsors
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.people.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: yomikiru
          plugin_people: yes
          plugin_people_types: contributors, sponsors
      - name: Sponsors goal
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.sponsors.svg
          token: ${{ secrets.METRICS_TOKEN_PERSONAL }}
          base: ""
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_past: yes
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: stargazer classic charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 6
          plugin_languages_analysis_timeout: 15